apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodenetworkstates.k8s.cni.cncf.io
spec:
  group: k8s.cni.cncf.io
  names:
    kind: NodeNetworkState
    listKind: NodeNetworkStateList
    plural: nodenetworkstates
    singular: nodenetworkstate
  scope: Cluster
  version: v1alpha1
  subresources:
   # status enables the status subresource.
    status: {}
