apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodenetworkconfigurationpolicies.k8s.cni.cncf.io
spec:
  group: k8s.cni.cncf.io
  names:
    kind: NodeNetworkConfigurationPolicy
    listKind: NodeNetworkConfigurationPolicyList
    plural: nodenetworkconfigurationpolicies
    singular: nodenetworkconfigurationpolicy
  scope: Cluster
  version: v1alpha1
