apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-network-operator
  namespace: node-network-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: node-network-operator
  template:
    metadata:
      labels:
        name: node-network-operator
    spec:
      serviceAccountName: node-network-operator
      containers:
        - name: node-network-operator
          image: mlnx-operator:latest
          securityContext:
            privileged: true
          volumeMounts:
          - name: udev
            mountPath: /etc/udev
          - name: sys
            mountPath: /sys
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - node-network-operator
          imagePullPolicy: IfNotPresent 
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "node-network-operator"
      volumes:
      - name: udev
        hostPath:
          path: /etc/udev
      - name: sys
        hostPath:
          path: /sys
